# Generated by Django 5.1.6 on 2025-02-28 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mecanicos", "0001_initial"),
        ("pecas", "0001_initial"),
        ("servicos", "0001_initial"),
        ("veiculos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrdemServico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_emissao", models.DateField(auto_now_add=True)),
                ("data_conclusao", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aberto", "Aberto"),
                            ("andamento", "Em andamento"),
                            ("finalizado", "Finalizado"),
                        ],
                        default="aberto",
                        max_length=20,
                    ),
                ),
                ("descricao_defeito", models.TextField()),
                (
                    "valor_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "mecanico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mecanicos.mecanico",
                    ),
                ),
                (
                    "veiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="veiculos.veiculo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrdemServicoPeca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.IntegerField(default=1)),
                (
                    "ordem_servico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ordens.ordemservico",
                    ),
                ),
                (
                    "peca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pecas.peca"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ordemservico",
            name="pecas",
            field=models.ManyToManyField(
                through="ordens.OrdemServicoPeca", to="pecas.peca"
            ),
        ),
        migrations.CreateModel(
            name="OrdemServicoServico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.IntegerField(default=1)),
                (
                    "ordem_servico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ordens.ordemservico",
                    ),
                ),
                (
                    "servico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="servicos.servico",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ordemservico",
            name="servicos",
            field=models.ManyToManyField(
                through="ordens.OrdemServicoServico", to="servicos.servico"
            ),
        ),
    ]
