# Generated by Django 5.1.6 on 2025-02-28 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ordens", "0001_initial"),
        ("pecas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordemservico",
            name="pecas",
            field=models.ManyToManyField(
                blank=True, through="ordens.OrdemServicoPeca", to="pecas.peca"
            ),
        ),
    ]
