# Generated by Django 5.1.6 on 2025-02-28 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MetricasDashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_os", models.IntegerField(default=0)),
                (
                    "total_faturamento",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("data_atualizacao", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
